Require for Maintenance.php was wrong
reedy@ubuntu64-esxi:~/mediawiki/trunk/extensions/CodeReview$ php svnImport.php  
Warning: require(/home/reedy/mediawiki/trunk/extensions/CodeReview/../../maintenance/Maintenance.php): failed to open stream: No such file or directory in /home/reedy/mediawiki/trunk/extensions/CodeReview/svnImport.php on line 7

Fatal error: require(): Failed opening required '/home/reedy/mediawiki/trunk/extensions/CodeReview/../../maintenance/Maintenance.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/reedy/mediawiki/trunk/extensions/CodeReview/svnImport.php on line 7


git-svn-id: svn+ssh://svn.wikimedia.org/svnroot/mediawiki/trunk@70824 dd0e9695-b195-4be7-bd10-2dea1a65a6b6